---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  schemas:
    errors_object:
      type: object
      properties:
        errors:
          "$ref": "#/components/schemas/errors_map"
    errors_map:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
paths:
  "/users":
    get:
      summary: list users
      tags:
      - Users
      responses:
        '200':
          description: successful
          content: {}
    post:
      summary: create user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: invalid_request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    first_name:
                      type: string
                    last_name:
                      type: string
                    email:
                      type: string
              required:
              - first_namelast_nameemail
  "/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      tags:
      - Users
      responses:
        '200':
          description: successful
          content: {}
        '404':
          description: not_found
          content: {}
    patch:
      summary: update user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
          content: {}
        '404':
          description: not_found
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    first_name:
                      type: string
                    last_name:
                      type: string
                    email:
                      type: string
    put:
      summary: update user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
          content: {}
        '404':
          description: not_found
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    first_name:
                      type: string
                    last_name:
                      type: string
                    email:
                      type: string
    delete:
      summary: delete user
      tags:
      - Users
      responses:
        '204':
          description: no_content
          content: {}
        '404':
          description: not_found
          content: {}
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
